name: Ajouter une image de chat
on:
  push:
    branches:
      - main

jobs:
  generate-cat-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Télécharger une image de chat
        run: |
          curl -o cat.jpg https://cataas.com/cat  # Télécharge l'image du chat

      - name: Mettre à jour README.md
        run: |
          echo "![Chat aléatoire](cat.jpg)" > cat_image.md  # Crée un fichier markdown avec l'image
          cat README.md cat_image.md > temp_readme.md  # Ajoute le fichier cat_image.md au README
          mv temp_readme.md README.md  # Remplace l'ancien README avec le nouveau

      - name: Commit et push les changements
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Ajout d'une image de chat au README"
          git push origin main